### ISSUE TITLE
페이지 간 상호작용

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#17]
## ⚙️ ISSUE
- 구성 완료된 페이지끼리 상호작용할 수 있도록 기능을 구현한다

## 📄 To-Do
하민
- [x] 메인화면 > 목적지 설정 버튼 > 목적지 설정 페이지
- [x] 메인화면 > 시작 버튼 > 카메라 작동
- [x] 앱 최초 접속 시 프로필 설정 페이지로 시작 (임시로 목적지 설정 페이지로 이동)

승민
- [x] 목적지 설정 페이지 > 뒤로가기 버튼 > 메인화면
- [x] 목적지 설정 페이지 > 완료 버튼 > (정보 저장 후) 메인화면
- [x] 프로필 설정 페이지 구성
- [x] 앱 최초 구동 여부에 따른 프로필 설정 페이지 버튼 반응 로직 변경
