### ISSUE TITLE
메뉴판 화면 구성

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#19]
## ⚙️ ISSUE
- 메뉴판 화면 UI를 구성한다.

## 📄 To-Do
- [x] 버튼 구성 (뒤로가기, 장바구니)
- [x] 음식 컨테이너 구성 (음식 사진, 음식 이름, 가격)
- [x] 뒤로가기 기능 구현 (홈페이지로 이동)
- [x] 다른 버튼들은 클릭 시 인식된다는 로그만 출력한다.
