### ISSUE TITLE
메인화면 UI 구성

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#2]
## ⚙️ ISSUE
- 메인화면 UI를 구성한다.

## 📄 To-Do
- [x] 앱 이름 작성 (화면 상단 FoodiePass)
- [x] 시작 버튼 구성
- [x] 여행지 표시 박스
- [x] 프로필 설정 버튼
- [x] 여행지 설정 버튼
- [x] 'made by..' 문구 추가

**Comment by Syun9274** [comment]
- [ ] 배경화면 흰색으로 설정
