### ISSUE TITLE
장바구니 페이지

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#25]
## ⚙️ ISSUE
- 장바구니 페이지 UI를 구성한다

## 📄 To-Do
- [ ] 선택한 음식 리스트
- [ ] 총 가격 정보 제공
- [ ] 음식 삭제 기능
