### ISSUE TITLE
전반적인 UI 통일

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#31]
## ⚙️ ISSUE
- 사용하는 아이콘, 배경색, 기타 등등 세부적인 UI 요소를 통일한다.

## 📄 To-Do
- [ ] 사용하는 아이콘 통일
- [ ] 사용하는 배경색 흰색으로 통일
- [ ] 사용하는 버튼 통일
- [ ] AppBar 형식 통일
