### ISSUE TITLE
디자인 수정

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#40]
## ⚙️ ISSUE
- 일부 디자인을 수정한다

## 📄 To-Do
- [x] 메인화면 UI 화면 크기를 초과하는 현상 수정
- [x] 추천 메뉴를 부각시키는 디자인 구성
- [x] 장바구니 UI 변경 (텍스트가 길어졌을 때 줄 내림 생기지 않도록 방어)
