### ISSUE TITLE
언어와 통화 설정 페이지

### ISSUE THREAD

**Issue by Syun9274** [Team-FoodiePass/FoodiePass-Android#7]
## ⚙️ ISSUE
- 언어와 통화 설정 페이지 UI를 구성한다.

## 📄 To-Do
- [x] 언어 리스트 박스 구성
- [x] 통화 리스트 박스 구성
- [x] 완료 버튼 구성
- [x] 뒤로가기 버튼 구성
- [x] 타이틀 텍스트 구성

**Comment by Syun9274** [comment]
merge 실수로 인해 branch 재작업
